name: Code Quality Check

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # a. Установка необходимых файлов из requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # b. Предварительная установка pycodestyle
    - name: Install pycodestyle
      run: pip install pycodestyle

    # c. Внутренний скрипт для проверки на наличие ошибок
    - name: Run pycodestyle
      run: |
        # Проверяем все python файлы в проекте
        echo "Checking code style with pycodestyle..."
        pycodestyle --count . || exit 1
        echo "No code style issues found."
